In [144]:
import polars as pl
import pandas as pd

import dask.dataframe as dd
import dask.array as da
import dask.bag as db

from sqlalchemy import create_engine, text
from sqlalchemy import MetaData
from sqlalchemy import Table, Column, Integer, String, Float # pour pouvoir préciser les types

import psycopg2
import os

# Import du Data Set

## via Dask à partir d'un CSV

In [7]:
DIR="C:/Users/User/Documents/MesProjets/projet_python/AnalyseDataToulouse"
url = DIR + "/data/DataArbresToulouse_1ereHomogénéisation.csv"

In [82]:
ddf = dd.read_csv(urlpath= url,
                 blocksize= "5MB",
                 dtype={'cultivar_variete': 'str',
       'date_plantation': 'str',
       'hauteur_approx_forestry': 'str',
       'hybride': 'str',
       'quartier': 'float64',
       'remarquable': 'str'}).set_index('id')

In [83]:
ddf

Dask DataFrame Structure:
              longitude latitude famille   genre  espece hybride cultivar_variete stade_dev   forme hauteur_approx_forestry remarquable date_plantation territoire quartier commune code_insee      lon      lat
npartitions=4
1               float64  float64  string  string  string  string           string    string  string                  string      string          string     string  float64  string      int64  float64  float64
29992               ...      ...     ...     ...     ...     ...              ...       ...     ...                     ...         ...             ...        ...      ...     ...        ...      ...      ...
57742               ...      ...     ...     ...     ...     ...              ...       ...     ...                     ...         ...             ...        ...      ...     ...        ...      ...      ...
94765               ...      ...     ...     ...     ...     ...              ...       ...     ...                     ...         ...             ...        ...      ...     ...        ...      ...      ...
132405              ...      ...     ...     ...     ...     ...              ...       ...     ...                     ...         ...             ...        ...      ...     ...        ...      ...      ...
Dask Name: setindex, 3 expressions
Expr=SetIndex(frame=ArrowStringConversion(frame=FromMapProjectable(6803b8b)), _other='id', options={})

In [55]:
ddf.partitions[0:2]

Dask DataFrame Structure:
              longitude latitude famille   genre  espece hybride cultivar_variete stade_dev   forme hauteur_approx_forestry remarquable date_plantation territoire quartier commune code_insee      lon      lat
npartitions=2
1               float64  float64  string  string  string  string           string    string  string                  string      string          string     string  float64  string      int64  float64  float64
29992               ...      ...     ...     ...     ...     ...              ...       ...     ...                     ...         ...             ...        ...      ...     ...        ...      ...      ...
57742               ...      ...     ...     ...     ...     ...              ...       ...     ...                     ...         ...             ...        ...      ...     ...        ...      ...      ...
Dask Name: partitions, 4 expressions
Expr=Partitions(frame=SetIndex(frame=ArrowStringConversion(frame=FromMapProjectable(6803b8b)), _other='id', options={}), partitions=[0, 1])

Attention, `compute()` peut être couteux pour les gros dataframe puisqu'il oblige à lire entièrement les données, pas de manière "lazy" donc.

In [64]:
ddf.compute()

,longitude,latitude,famille,genre,espece,hybride,cultivar_variete,stade_dev,forme,hauteur_approx_forestry,remarquable,date_plantation,territoire,quartier,commune,code_insee,lon,lat
id,,,,,,,,,,,,,,,,,,
1,1.459384,43.591148,Betulacees,Carpinus,betulus,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,CENTRE,5.0,Toulouse,3118,1.459384,43.591148
2,1.396757,43.571969,Pinacees,Pinus,pinea,<NA>,<NA>,3 - Adulte,2 - Libre,<NA>,<NA>,<NA>,SUD,17.0,Toulouse,3120,1.396757,43.571969
3,1.454729,43.597842,Platanacees,Platanus,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,CENTRE,3.0,Toulouse,3118,1.454729,43.597842
4,1.437363,43.596454,Myrtacees,Callistemon,laevis,<NA>,<NA>,2 - Jeune adulte,2 - Libre,<NA>,<NA>,<NA>,CENTRE,6.0,Toulouse,3115,1.437363,43.596454
12,1.434498,43.598185,Famille_inconnue,Tilia,henryana,<NA>,<NA>,1 - Jeune,2 - Libre,<NA>,<NA>,2020-03-04,CENTRE,6.0,Toulouse,3115,1.434498,43.598185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132401,1.445651,43.605613,Magnoliacees,Magnolia,grandiflora,<NA>,cv.Nantais,1 - Jeune,2 - Libre,<NA>,<NA>,2024-01-01,CENTRE,1.0,Toulouse,3117,1.445651,43.605613
132402,1.445653,43.605089,Magnoliacees,Magnolia,grandiflora,<NA>,cv.Nantais,1 - Jeune,2 - Libre,<NA>,<NA>,2024-01-01,CENTRE,1.0,Toulouse,3117,1.445653,43.605089
132403,1.445641,43.603776,Magnoliacees,Magnolia,grandiflora,<NA>,cv.Nantais,1 - Jeune,2 - Libre,<NA>,<NA>,2024-01-01,CENTRE,1.0,Toulouse,3117,1.445641,43.603776
132404,1.445639,43.603462,Magnoliacees,Magnolia,grandiflora,<NA>,cv.Nantais,1 - Jeune,2 - Libre,<NA>,<NA>,2024-01-01,CENTRE,1.0,Toulouse,3117,1.445639,43.603462
132405,1.398201,43.575740,Pinacees,Pinus,pinea,<NA>,<NA>,3 - Adulte,3 - Semi libre,<NA>,<NA>,<NA>,SUD,17.0,Toulouse,3120,1.398201,43.575740

In [61]:
ddf.lon.mean()

In [62]:
ddf.lon.mean().compute()

np.float64(1.430313879666031)

Attention, une moyenne de longitude n'a pas de réel sens.

# Modification directe SQl

Le but est de modifiers la base sql directemt par partition. Cela permet d'éviter de charger en mémoires de trop gros tableaux.

On pourrait faire toutes les modifications avec dask puis sauver au format CSV avant de migrer vers la database Postgre. Toujours pour des raisons de copie, de mémoire, on va plutot migrer le csv original dans la database puis faire les modifs à partir de celle ci.

# Migration des données csv vers la database sql

In [67]:
# Créer la connexion SQLAlchemy pour PostgreSQL
user = os.environ["PG_USER"]
password = os.environ["PG_PASSWORD"]

engine = create_engine(f"postgresql+psycopg2://{user}:{password}@localhost:5432/test_db")

In [69]:
ddf.columns

Index(['longitude', 'latitude', 'famille', 'genre', 'espece', 'hybride',
       'cultivar_variete', 'stade_dev', 'forme', 'hauteur_approx_forestry',
       'remarquable', 'date_plantation', 'territoire', 'quartier', 'commune',
       'code_insee', 'lon', 'lat'],
      dtype='str')

In [72]:
type(ddf.columns)

pandas.Index

In [74]:
column_list = ddf.columns.tolist()
type(column_list)

list

In [78]:
columns = ['id'] + column_list

## 1 ere option

In [146]:
# Create an iterable that will read "chunksize=1000" rows
# at a time from the CSV file
for df in pd.read_csv(url,chunksize=10000):
  df.to_sql(
    'Arbres_1st_homogeneisation', 
    engine,
    index=False,
    # if the table already exists, append this data
    if_exists='append',
  )

Le problème est que les types des colonnes peut ne pas etre respecté. Voir la méthode en dessous.

## 2 nd option

In [136]:
my_types= [Integer, Float, Float, String, String, String, String, String, String, String, String, String, String, String, Float, String, Integer, Float, Float]
# Il faut au préalable importer les classes sqlAlchemy (voir début du script)

In [138]:
my_dict = dict(zip(columns,my_types))

In [139]:
print(my_dict)

{'id': <class 'sqlalchemy.sql.sqltypes.Integer'>, 'longitude': <class 'sqlalchemy.sql.sqltypes.Float'>, 'latitude': <class 'sqlalchemy.sql.sqltypes.Float'>, 'famille': <class 'sqlalchemy.sql.sqltypes.String'>, 'genre': <class 'sqlalchemy.sql.sqltypes.String'>, 'espece': <class 'sqlalchemy.sql.sqltypes.String'>, 'hybride': <class 'sqlalchemy.sql.sqltypes.String'>, 'cultivar_variete': <class 'sqlalchemy.sql.sqltypes.String'>, 'stade_dev': <class 'sqlalchemy.sql.sqltypes.String'>, 'forme': <class 'sqlalchemy.sql.sqltypes.String'>, 'hauteur_approx_forestry': <class 'sqlalchemy.sql.sqltypes.String'>, 'remarquable': <class 'sqlalchemy.sql.sqltypes.String'>, 'date_plantation': <class 'sqlalchemy.sql.sqltypes.String'>, 'territoire': <class 'sqlalchemy.sql.sqltypes.String'>, 'quartier': <class 'sqlalchemy.sql.sqltypes.Float'>, 'commune': <class 'sqlalchemy.sql.sqltypes.String'>, 'code_insee': <class 'sqlalchemy.sql.sqltypes.Integer'>, 'lon': <class 'sqlalchemy.sql.sqltypes.Float'>, 'lat': <class 'sqlalchemy.sql.sqltypes.Float'>}

In [143]:
# Load in the data
df = pd.read_csv(
   url,
    names=columns,
    nrows=1,  # load in the first 1000 rows
    header = 0
)


# Save the data from dataframe to
# postgres table "iris_dataset"
df.to_sql(
    'Arbres_1st_homogeneisation', 
    engine,
    index=False,
    dtype = my_dict
)

1

Une fois la table crée à partir du csv et les colonnes inféré, on supprime les données de la table (pas la structure) et on fait dans Postgre : 

```
DELETE FROM iris_dataset;

\COPY iris_dataset FROM 'downloads/iris.csv' DELIMITER ',' CSV;
```

Ainsi on aura le bon type et les données récupérées dans leur entièreté.

# Début du Nettoyage